services:
  # Servidor Web (Nginx)
  nginx:
    image: nginx:alpine
    container_name: sdi-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - sdi-network
    depends_on:
      - app

  # Aplicación (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sdi-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - sdi-network
    depends_on:
      - db

  # Base de Datos (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: sdi-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: sdi_test
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
    volumes:
      - ./docker-compose/pgsql:/var/lib/postgresql/data
    networks:
      - sdi-network

networks:
  sdi-network:
    driver: bridge
